# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWebEngineWidgets import QWebEngineView
from PyQt5.QtCore import QUrl

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(930, 591)
        MainWindow.setMinimumSize(QtCore.QSize(700, 500))
        MainWindow.setStyleSheet("\n"
"QLineEdit {\n"
"  border-radius: 8px;\n"
"  border: 1px solid #e0e4e7;\n"
"  padding: 5px 15px;\n"
"    background-color: rgb(154, 153, 150);\n"
"}\n"
"\n"
"QMainWindow{\n"
"    background-color: rgb(5, 19, 26);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"  border: 1px solid #d0e3ff;\n"
"}\n"
"QLineEdit::placeholder {\n"
"  color: #767e89;\n"
"}")
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topBar = QtWidgets.QFrame(self.centralwidget)
        self.topBar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.topBar.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.topBar.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.topBar.setObjectName("topBar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.topBar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.backBtn = QtWidgets.QPushButton(self.topBar)
        self.backBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/backwardIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backBtn.setIcon(icon)
        self.backBtn.setIconSize(QtCore.QSize(20, 20))
        self.backBtn.setFlat(True)
        self.backBtn.setObjectName("backBtn")
        self.horizontalLayout.addWidget(self.backBtn)
        
#RELOAD BUTTON CODE
        self.reloadBtn = QtWidgets.QPushButton(self.topBar)
        self.reloadBtn.setText("")
        self.icon1 = QtGui.QIcon()
        self.icon1.addPixmap(QtGui.QPixmap("icons/reloadIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reloadBtn.setIcon(self.icon1)
        self.reloadBtn.setIconSize(QtCore.QSize(22, 22))
        self.reloadBtn.setFlat(True)
        self.reloadBtn.setObjectName("reloadBtn")
        self.horizontalLayout.addWidget(self.reloadBtn)
        
        
#FORWARD BUTTON CODE
        self.forwardBtn = QtWidgets.QPushButton(self.topBar)
        self.forwardBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/forwardIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.forwardBtn.setIcon(icon2)
        self.forwardBtn.setIconSize(QtCore.QSize(20, 20))
        self.forwardBtn.setFlat(True)
        self.forwardBtn.setObjectName("forwardBtn")
        self.horizontalLayout.addWidget(self.forwardBtn)
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.horizontalLayout.addItem(spacerItem)

#ADDRESS BAR CODE
        self.addressBar = QtWidgets.QLineEdit(self.topBar)
        self.addressBar.setStyleSheet("")
        self.addressBar.setObjectName("addressBar")
        self.horizontalLayout.addWidget(self.addressBar)

#SEARCH BUTTON CODE
        self.searchBtn = QtWidgets.QPushButton(self.topBar)
        self.searchBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/searchIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchBtn.setIcon(icon3)
        self.searchBtn.setIconSize(QtCore.QSize(22, 22))
        self.searchBtn.setFlat(True)
        self.searchBtn.setObjectName("searchBtn")
        self.horizontalLayout.addWidget(self.searchBtn)
        spacerItem1 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.horizontalLayout.addItem(spacerItem1)

#SETTINGS BUTTON CODE
        self.settingsBtn = QtWidgets.QPushButton(self.topBar)
        self.settingsBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/settingIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsBtn.setIcon(icon4)
        self.settingsBtn.setIconSize(QtCore.QSize(25, 25))
        self.settingsBtn.setFlat(True)
        self.settingsBtn.setObjectName("settingsBtn")
        self.horizontalLayout.addWidget(self.settingsBtn)
        self.verticalLayout.addWidget(self.topBar)

#WEBVIEWER WIDGET:
        self.widget = QWebEngineView(self.centralwidget)
        self.widget.setStyleSheet("QWidget {\n"
" border-radius: 8px;\n"
"    background-color: rgb(16, 32, 45);\n"
"\n"
"}")
        
        self.widget.load(QUrl("https://www.google.com"))
        self.addressBar.setText("https://www.google.com")
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        

#WEB BROWSING FUNCTIONS:
        def searchEvent():
            link = self.addressBar.text()
            if link.startswith("http") == True:
                self.widget.load(QUrl(link))
                updateSearchBar(link)
            else:
                link1 = {f"https://google.com/search?q={link}"}
                self.widget.load(QUrl("https://www.google.com"))
                updateSearchBar("https://www.google.com")
        self.addressBar.returnPressed.connect(searchEvent)
        self.searchBtn.clicked.connect(searchEvent)
        
        def updateSearchBar(link:str):
            self.addressBar.setText(link)

        def loadingStarted():
            self.iconLoading = QtGui.QIcon()
            self.iconLoading.addPixmap(QtGui.QPixmap("icons/loadingIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            self.reloadBtn.setIcon(self.iconLoading)
        self.widget.loadStarted.connect(loadingStarted)

        def loadingEnd():
            self.reloadBtn.setIcon(self.icon1)
        self.widget.loadFinished.connect(loadingEnd)

        def reloadPage():
            self.widget.reload()
        self.reloadBtn.clicked.connect(reloadPage)

        def forwardPage():
            self.widget.forward()
        self.forwardBtn.clicked.connect(forwardPage)

        def backPage():
            self.widget.back()
        self.backBtn.clicked.connect(backPage)
        website = self.widget.url()
        updateSearchBar(website)
        
            

#WEB BROWSING FUNCTIONS END


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Monochrome v0.1"))
        self.addressBar.setPlaceholderText(_translate("MainWindow", "Search Google or Enter a URL"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
