# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(694, 527)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(694, 527))
        Dialog.setMaximumSize(QtCore.QSize(694, 527))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.about = QtWidgets.QWidget()
        self.about.setObjectName("about")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.about)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.about)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_6 = QtWidgets.QLabel(self.about)
        font = QtGui.QFont()
        font.setItalic(True)
        font.setUnderline(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.about)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setItalic(False)
        font.setUnderline(False)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(0, 500, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.tabWidget.addTab(self.about, "")
        self.appearance = QtWidgets.QWidget()
        self.appearance.setObjectName("appearance")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.appearance)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.themeSelect = QtWidgets.QHBoxLayout()
        self.themeSelect.setObjectName("themeSelect")
        self.themeLabel = QtWidgets.QLabel(self.appearance)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        self.themeLabel.setFont(font)
        self.themeLabel.setStyleSheet("\n"
"QLineEdit {\n"
"  border-radius: 8px;\n"
"  border: 1px solid #e0e4e7;\n"
"  padding: 5px 15px;\n"
"    background-color: rgb(154, 153, 150);\n"
"}\n"
"\n"
"QMainWindow{\n"
"    background-color: rgb(5, 19, 26);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"  border: 1px solid #d0e3ff;\n"
"}\n"
"QLineEdit::placeholder {\n"
"  color: #767e89;\n"
"}\n"
"QDialog{\n"
"background-color:rgb(5,19,26)\n"
"}")
        self.themeLabel.setObjectName("themeLabel")
        self.themeSelect.addWidget(self.themeLabel)
        self.label_5 = QtWidgets.QLabel(self.appearance)
        self.label_5.setObjectName("label_5")
        self.themeSelect.addWidget(self.label_5)
        self.verticalLayout_4.addLayout(self.themeSelect)
        self.light = QtWidgets.QRadioButton(self.appearance)
        self.light.setObjectName("light")
        self.verticalLayout_4.addWidget(self.light)
        self.dark = QtWidgets.QRadioButton(self.appearance)
        self.dark.setChecked(True)
        self.dark.setObjectName("dark")
        self.verticalLayout_4.addWidget(self.dark)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.appearance)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.appearance)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.radioButton = QtWidgets.QRadioButton(self.appearance)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_5.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.appearance)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_5.addWidget(self.radioButton_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(20,250, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        self.verticalLayout_3.addItem(spacerItem3)
        self.tabWidget.addTab(self.appearance, "")
        self.advanced = QtWidgets.QWidget()
        self.advanced.setObjectName("advanced")
        self.tabWidget.addTab(self.advanced, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Settings- Monochrome"))
        self.label.setText(_translate("Dialog", "MONOCHROME WEB BROWSER BETA"))
        self.label_6.setText(_translate("Dialog", "VERSION 0.1B"))
        self.label_2.setText(_translate("Dialog", "Unstable release with missing features for version 0.1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.about), _translate("Dialog", "About"))
        self.themeLabel.setText(_translate("Dialog", "THEME"))
        self.label_5.setText(_translate("Dialog", "Choose the look of your web browser"))
        self.light.setText(_translate("Dialog", "Light"))
        self.dark.setText(_translate("Dialog", "Dark"))
        self.label_4.setText(_translate("Dialog", "HOME BUTTON"))
        self.label_3.setText(_translate("Dialog", "Enable the home button to quickly jump back to your favourate homepage and surf the web faster"))
        self.radioButton.setText(_translate("Dialog", "Enable Home Button"))
        self.radioButton_2.setText(_translate("Dialog", "Disable Home Button"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.appearance), _translate("Dialog", "Appearance"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.advanced), _translate("Dialog", "Advanced"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
